functionsDirectory = "/Users/siddon/eng/tidb-cloud-zero-browser/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
plugins = []
redirects = []

[build]
publish = "/Users/siddon/eng/tidb-cloud-zero-browser"
publishOrigin = "config"
functions = "/Users/siddon/eng/tidb-cloud-zero-browser/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"